### ISSUE TITLE
Transaction table issues

### ISSUE THREAD

**Issue by RuubioRuub** [DennisDoksani/Code_Generation_2223k_FrontEnd#14]
Two issues occur in TransactionTable.vue: 

- The form for the filters disappear when you try to type something
- It can not display the transactions timestamp

**Comment by Josh684077** [comment]
- there was a "display: none" style trait in the form, method to make it visible has been changed so that it toggles between block and none
- timestamp was loaded in json with a different variable name then you were importing, "time" instead of "timestamp". Also sliced it to remove seconds from the time
